version: '3.8'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    image: my-python-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - database
    networks:
      - app_network

  frontend:
    image: my-nodejs-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      API_URL: http://backend:5000
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
