---
- hosts: app_servers
  become: yes
  vars_files:
    - ./secrets.yml

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install Docker
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Install Docker CE
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Create application directory
      file:
        path: /opt/myapp
        state: directory
        mode: '0755'

    - name: Copy application files
      copy:
        src: /home/ubuntu/React-django/
        dest: /opt/myapp/

    - name: Create .env file from template
      template:
        src: ./templates/.env.j2
        dest: /opt/myapp/.env
        mode: '0600'

    - name: Start application with Docker Compose
      command: docker-compose up -d
      args:
        chdir: /opt/myapp
